### ISSUE TITLE
Build failure when running 'pip install sep'

### ISSUE THREAD

**Issue by kboone** [kbarbary/sep#28]
Something broke when installing via pip. I get the following error:

```
kyle@julebrus:~/supernova/sep$ pip install sep
Collecting sep
  Using cached sep-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-JD82YD/sep/setup.py", line 25, in <module>
        version = re.findall(r"__version__ = \"(.*?)\"", open("sep.pyx").read())[0]
    IOError: [Errno 2] No such file or directory: 'sep.pyx'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JD82YD/sep
```

Looks like in a368d62baa26a0f1bc23e80f9a2fe14903d06dee, a helper was added that checks sep.pyx for the version, but sep.pyx never gets copied to the pip build directory.

**Comment by kbarbary** [comment]
Just uploaded a new version (0.5.1) with the fix.
